### ISSUE TITLE
linux 5.13 - compilation error

### ISSUE THREAD

**Issue by mikefaille** [HinTak/sound-usb-dkms#5]
To reproduce : 

```
make -C /lib/modules/`uname -r`/build M=`pwd`/sound/usb clean
make -C /lib/modules/`uname -r`/build M=`pwd`/sound/usb modules
make: Entering directory '/usr/src/linux-headers-5.13.0-7614-generic'
  CC [M]  /home/michael/src/sound-usb-dkms/sound/usb/misc/ua101.o
/home/michael/src/sound-usb-dkms/sound/usb/misc/ua101.c:22:25: error: expected declaration specifiers or ‘...’ before string constant
   22 | MODULE_SUPPORTED_DEVICE("{{Edirol,UA-101},{Edirol,UA-1000}}");
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:280: /home/michael/src/sound-usb-dkms/sound/usb/misc/ua101.o] Error 1
make[1]: *** [scripts/Makefile.build:523: /home/michael/src/sound-usb-dkms/sound/usb/misc] Error 2
make: *** [Makefile:1859: /home/michael/src/sound-usb-dkms/sound/usb] Error 2
make: Leaving directory '/usr/src/linux-headers-5.13.0-7614-generic'

```

**Comment by HinTak** [comment]
Wrong branch - you seems to be on one of the v5.11-* branches? Besides, you probably should use
https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module instead.

There is a small one-line difference between the default (master) branch here and the default (v5.12-sound-master) branch over there. The one-line patch patches/0001-Reverse-apply-b6cc78da367cf9aac7ae77bbea73ecca43a704.patch is to be automatically applied the dkms way here, but already applied over at Focusrite-Scarlett-on-Linux/sound-usb-kernel-module .

Just remove /home/michael/src/sound-usb-dkms and clone https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module fresh, and you'd be fine with building on 5.13 .

**Comment by mikefaille** [comment]
Yes you're right. I was on the wrong branch.

**Comment by mikefaille** [comment]
Also, thank you to redirect me to the right project.
